### ISSUE TITLE
Icons: On smaller resolutions, `radius` doesn't work out nice

### ISSUE THREAD

**Issue by FokkeZB** [FokkeZB/TiCons-CLI#14]

**Comment by cbrunnkvist** [comment]
It must be some sort of rounding mistake? I haven't looked at the code, but I see the effects: the "recommended" iOS-mimicking `-r 10` in particular seem to misalign the corners. 

Attaching an example blow-up of an _hdpi_ icon for reference.

![skarmavbild 2015-09-04 kl 18 36 27](https://cloud.githubusercontent.com/assets/34006/9682813/531e4bc0-5334-11e5-9380-4a47c2cc00b8.png)

**Comment by FokkeZB** [comment]
The calculation is here:

https://github.com/FokkeZB/TiCons-CLI/blob/master/lib/jobs.js#L248-L256

I can't look at it right now. Can you give it a try and play with the above?

**Comment by cbrunnkvist** [comment]
Thanks for the hint, I'll see what I can do.

**Comment by AppsolutEinfach** [comment]
There is a 1-pixel offset on the right side.
The underlying code from http://www.rubblewebs.co.uk/imagemagick/display_example.php?example=69 is wrong (see the wrong image result there).

`ImagickDraw::roundRectangle()` takes coordinates of top left corner and bottom right corner
(see http://php.net/manual/de/imagickdraw.roundrectangle.php).
The coordinates of these corners obviously are (0,0) and (width-1,height-1).

In my opinion, line 256 should be

    .in('-draw').in('roundRectangle 0,0 ' + (spec.width - 1) + ',' + (spec.height - 1) + ' ' + radius + ',' + radius);

**Comment by cbrunnkvist** [comment]
That's exactly the reason, great spotting @AppsolutEinfach ! 
![skarmavbild 2015-09-30 kl 21 56 05](https://cloud.githubusercontent.com/assets/34006/10196675/39167e52-67be-11e5-9b7c-7b2820a80df5.png)

**Comment by AppsolutEinfach** [comment]
@cbrunnkvist Thanks for correcting!
