### ISSUE TITLE
I can't use XXXHDPI now

### ISSUE THREAD

**Issue by vdesdoigts** [FokkeZB/TiCons-CLI#30]
Why have you change max dpi to XXHDPI ?
I only use the assets in xxxhdpi to generate the others, so I don't have my assets in xxhdpi originally, and if I use those in xxxhdpi they are not the right size.

**Comment by FokkeZB** [comment]
I changed the default max (and min, at mdpi) but you can still set it to xxxhdpi using `--max-dpi xxxhdpi`

**Comment by vdesdoigts** [comment]
Thanks !
