### ISSUE TITLE
Splashes are "square"

### ISSUE THREAD

**Issue by vdesdoigts** [FokkeZB/TiCons-CLI#31]
I use a png in 2208x2208 to generate my splashes, since the last version of ticons the generated splashes are "square".
Example: Default@2x.png is 960x960 instead of 640x960

**Comment by vdesdoigts** [comment]
Not coming from TiCons. My colleague didn't have this problem on his post.

**Comment by vdesdoigts** [comment]
He was on v0.11, in v0.12.1 it's buggy.

**Comment by xavierlacot** [comment]
I can confirm that splashes generation is broken. The following change did break it: https://github.com/FokkeZB/TiCons-CLI/commit/e42a48cbab3d8a107f87e95c04ea2bc22527d4ee#diff-6250865cbe8215106353c06e8a4f327dR278

To fix things, you must either:
 * remove the use of the `-flatten` option in https://github.com/FokkeZB/TiCons-CLI/blob/master/lib/jobs.js#L278
 * add a `alpha: true` option for all the splashes specs in https://github.com/FokkeZB/TiCons-CLI/blob/master/lib/specs.js#L193
