### ISSUE TITLE
CLI not creating Android Markplace Icon

### ISSUE THREAD

**Issue by DouglasHennrich** [FokkeZB/TiCons-CLI#34]
`ticons icons -r 20 -d ./icons -p android -a icon.png`

I get an `MarketplaceArtwork.png` but I don't get the Android's Icon with my Border Radius and `512x512` to upload to PlayStore

I need to add something else to generate the Android's PlayStore Icon?

Thanks

**Comment by FokkeZB** [comment]
You sure? I do:

https://github.com/FokkeZB/TiCons-CLI/blob/master/lib/specs.js#L336-L340

**Comment by DouglasHennrich** [comment]
~~~
[INFO]  Reading input dimensions
[INFO]  Starting 6 jobs
[INFO]  Generated: icons/platform/android/res/drawable-mdpi/appicon.png
[INFO]  Generated: icons/platform/android/res/drawable-hdpi/appicon.png
[INFO]  Generated: icons/platform/android/res/drawable-xhdpi/appicon.png
[INFO]  Generated: icons/MarketplaceArtwork.png
[INFO]  Generated: icons/app/assets/android/appicon.png
[INFO]  Generated: icons/platform/android/res/drawable-xxhdpi/appicon.png
[OK]    Generated 6 icons
~~~

strange... now I get this image... oO
don't know what went wrong last time I tested... anyway... Thanks Fokke.

Another question... how can I use the Assets command ?

I always get `[ERROR] Could not identify input density.`

Thanks

**Comment by FokkeZB** [comment]
This error happens if the path you've given to `ticons assets` isn't a subdirectory of one of those mentioned in the readme:
https://github.com/FokkeZB/TiCons-CLI/blob/master/README.md#assets

If you don't give it a path it will check if one of the above exists.

**Comment by DouglasHennrich** [comment]
Thanks
