### ISSUE TITLE
v0.14.0 - which iOS icons should be generated?

### ISSUE THREAD

**Issue by cbrunnkvist** [FokkeZB/TiCons-CLI#35]
I was using ticons to generate splashes an icons for my project when I saw this message last week: 
```
-----------------------------------------
Update available: 0.14.0 (current: 0.13.3)
Run npm update -g ticons to update
-----------------------------------------
```

So, after heeding the upgrade hint (despite not seeing that release here on GitHub?) it now generates fewer images. Is that on purpose? What about -60, -small, appicon@3x and so on? Here is a diff in the difference in output of `icons -p android,iphone -m mdpi -M xdpi`.

```
--- 0.13.3	2015-09-07 14:43:30.000000000 +0700
+++ 0.14.0	2015-09-07 14:16:28.000000000 +0700
@@ -4,16 +4,7 @@
 [INFO]  Generated: ../iTunesConnect.png
 [INFO]  Generated: ../app/assets/iphone/iTunesArtwork@2x
 [INFO]  Generated: ../app/assets/iphone/iTunesArtwork
-[INFO]  Generated: ../app/assets/iphone/appicon@2x.png
 [INFO]  Generated: ../app/assets/iphone/appicon.png
-[INFO]  Generated: ../app/assets/iphone/appicon-Small@3x.png
-[INFO]  Generated: ../app/assets/iphone/appicon-Small@2x.png
-[INFO]  Generated: ../app/assets/iphone/appicon-Small.png
-[INFO]  Generated: ../app/assets/iphone/appicon-Small-40@2x.png
-[INFO]  Generated: ../app/assets/iphone/appicon-Small-40.png
-[INFO]  Generated: ../app/assets/iphone/appicon-60@3x.png
-[INFO]  Generated: ../app/assets/iphone/appicon-60@2x.png
-[INFO]  Generated: ../app/assets/iphone/appicon-60.png
 [INFO]  Generated: ../app/assets/android/appicon.png
 [INFO]  Generated: ../MarketplaceArtwork.png
-[OK]    Generated 18 icons
+[OK]    Generated 9 icons
```

**Comment by FokkeZB** [comment]
If your project is using the 5.0.0 beta SDK then it should generate the above because since 5.0.0 Titanium generates the icons for you. If if happens with earlier SDKs as well then that's an error. Please let me know.

**Comment by cbrunnkvist** [comment]
Aha, yeah that looks like a bug then: 
`Titanium Command-Line Interface, CLI version 3.4.2, Titanium SDK version 4.1.0.GA`

**Comment by FokkeZB** [comment]
I just tested with an 4.1.0.GA projects and there it generates all of them correctly. What do you have in your project's `tiapp.xml` for `<version />` exactly?

**Comment by cbrunnkvist** [comment]
Really? Weird. My version is set in the app config XML: `<sdk-version>4.1.0.GA</sdk-version>`, and I have according to `appc ti sdk` only `4.1.0.GA` installed. Do you perhaps have multiple ones installed and conflicting version preferences between Studio / CLI or something?

**Comment by FokkeZB** [comment]
TiCons just reads the `tiapp.xml` and sets that. Try running it with `-t` to see details.

**Comment by cbrunnkvist** [comment]
It says 5.0.0, just like in constants.js ... I had a look at the code and I think I see what's going on: `isProject` and the subsequent parsing of the tiapp.xml file happens _only unless_ `-d` is set. I didn't realize it initially but I was actually prepending the command line args with `-d ../project_root/` in my build script.

So, while it isn't exactly a bug, I was expecting the config to be found/looked for in outputDir...

**Comment by cbrunnkvist** [comment]
On a second thought, it should probably be considered a bug since https://github.com/FokkeZB/TiCons-CLI#smart-defaults complies with that said expectation :)

**Comment by FokkeZB** [comment]
Good catch! Fixed!
