### ISSUE TITLE
iphone icons

### ISSUE THREAD

**Issue by abada** [FokkeZB/TiCons-CLI#43]
when make an icon   2048*2048   to this path  iphone/iTunesArtwork@2x

and run ` ~/myproject $ ticons icons`

doesn`t generate iphone icons !

**Comment by abada** [comment]
Just created DefaultIcon.png

**Comment by FokkeZB** [comment]
Since Titanium 5.0 that's the only icon you need for iOS. Use the new `--sdk-version <version>` option to set it to e.g. 4.1.0 to get the old icons.

**Comment by abada** [comment]
I thought of that, but the old icons  still exists in SDK 5.0  when I do a new project in appc studio

**Comment by FokkeZB** [comment]
That depends on the template you select but yes, some still have the old ones. Which is OK, `DefaultIcon.png` will only be used to generate missing icons.

**Comment by abada** [comment]
Thank you :+1:
