### ISSUE TITLE
Setting default options

### ISSUE THREAD

**Issue by yomybaby** [FokkeZB/TiCons-CLI#49]
This is a question. :)
When `xxxhdpi` is input source, I have to give `input` and `max-dip` option every running.

```
ticons assets app/assets/android/images/res-xxxhdpi -M 640
```

Is there any way to set default setting?

Additionally,  xxxhdpi should have higher priority then `iphone/images`?
Because, xxxhdpi is bigger then @3x.
https://github.com/FokkeZB/TiCons-CLI/blob/master/lib/config.js#L423-L426

**Comment by FokkeZB** [comment]
Thanks @yomybaby !

**Comment by yomybaby** [comment]
Thanks. :+1
