### ISSUE TITLE
Wrong size configuration of android splashes? same configuration for long and not-long assets

### ISSUE THREAD

**Issue by davide-ensini** [FokkeZB/TiCons-CLI#52]
This has been bugging me for a while.. It looks like most (not all) of the android screens sizes in specs.js have the same width and length for both the long and not-long screen resolutions. 
E.g. 
exports['android-default-notlong-port-xxxhdpi'] = {
 [...]
  width: 1280,
  height: 1920,
 [...]
};
exports['android-default-long-port-xxxhdpi'] = {
 [...]
  width: 1280,
  height: 1920,
 [...]
};
This looks so obviously wrong that I'm wondering if I am missing something instead. 
If you can confirm this is a bug I'll be happy to submit a pull request to fix this.

**Comment by FokkeZB** [comment]
Yes, that must be wrong although I can't make much of http://docs.appcelerator.com/platform/latest/#!/guide/Icons_and_Splash_Screens-section-29004897_IconsandSplashScreens-PreviousRecommendations either. In the end it's always better to use 9-patch. You'll never be able to serve all devices with regular images.

But if you have a good suggestion for better sizes, please lmk.

**Comment by davide-ensini** [comment]
Yeah, I think you are right. I thought this was just a mistake, now I see this is a larger problem. 9-patch will do. Thanks
