### ISSUE TITLE
[ERROR] Could not find input images

### ISSUE THREAD

**Issue by yomybaby** [FokkeZB/TiCons-CLI#54]
Hi Fokke,
I found a bug.

After v0.22.0, 'ticons assets' got an error.

### How to reproduce
- Create new alloy titanium project
- Delete `app/assets/android/images/*`.
- Create `app/assets/android/images/res-xxxhdpi`, and put on image file.

And run `ticons assets`

v0.22.0 : `[ERROR] Could not find input images`
v0.21.2: It works properly

**Comment by FokkeZB** [comment]
Thanks @yomybaby! I've pushed a new version with a fix.

**Comment by yomybaby** [comment]
👍🏼 Thanks!!
