### ISSUE TITLE
windows phone 8 icon sizes

### ISSUE THREAD

**Issue by huzjakd** [FokkeZB/TiCons-CLI#56]
There is no option for choosing window phone 8 platform when generating icons.
Phonegap Build supports windows phone 8 with 2 icons 99x99 and 159x159 background if I'm not mistaking.
Is there a way to choose that, or custom generate icons?

**Comment by FokkeZB** [comment]
The CLI defaults to optimal settings for Titanium 5.2+

In the case of Windows this means for Titanium 5.1+ it only generates a `DefaultIcon.png` and Titanium will generate the other sizes. You can use the `--sdk-version` option to set it to an older Titanium version.

See this code for details:
https://github.com/FokkeZB/TiCons-CLI/blob/master/lib/specs.js#L829-L914
