### ISSUE TITLE
20pt Icons for iOS Notifications

### ISSUE THREAD

**Issue by joncursi** [FokkeZB/TiCons-CLI#57]
The smallest icon this library generates appears to be 29pt. However, iOS apps need a 20pt icon for notifications:

<img width="237" alt="screen shot 2016-09-19 at 11 20 38 am" src="https://cloud.githubusercontent.com/assets/4974609/18637670/31897040-7e5b-11e6-931a-862158621586.png">

Is there a way to produce 20pt icons with this library? I tried setting the `--min-dpi` flag, but the lowest this goes is 120dpi.

**Comment by FokkeZB** [comment]
@joncursi 20pt @2x and @4x means a 40px and 60px icons, both present:

- 40px: https://github.com/FokkeZB/TiCons-CLI/blob/master/lib/specs.js#L138
- 60px: https://github.com/FokkeZB/TiCons-CLI/blob/master/lib/specs.js#L58
