### ISSUE TITLE
NPM does not update to 0.23.1

### ISSUE THREAD

**Issue by focussing** [FokkeZB/TiCons-CLI#58]
Could you please fix this?
Thanks on forehand.

**Comment by FokkeZB** [comment]
@focussing I'm not sure what you mean. The current version is 0.23.0:
https://github.com/FokkeZB/TiCons-CLI/blob/master/package.json#L4

**Comment by focussing** [comment]
Hi Fokke,

Sorry, on this page it says 0.23.1.
https://www.npmjs.com/package/ticons

That's what confused me.

**Comment by FokkeZB** [comment]
Ah, the repo was out of date. OK, fixed that!
